### PR TITLE
openSUSE updates

### PR DESCRIPTION
**Pull request by kalxas**
Managed to complete the transition to otb 5.0.0, will continue with rest of packages soon.

### CODE REVIEW

**Comment by kalxas** [comment]
otb 5.2.0 packages are now added

**Comment by rkanavath** [comment]
merged!

**Comment by kalxas** [comment]
Thanks @rkanavath

**Comment by rkanavath** [comment]
are those packages ready for 5.2? where should I look for updates?

**Comment by kalxas** [comment]
https://build.opensuse.org/project/monitor/home:tzotsos

**Pull request merged**
